name: Run Scraper Once

on:
  workflow_dispatch:

jobs:
  run-once:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: true
        fetch-depth: 0   # لازم برای checkout شاخه دیگر

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        pip install playwright
        python -m playwright install --with-deps

    - name: Run scraper script
      run: python web_sc.py

    - name: Commit and push results
      run: |
        git config --local user.email "github-actions@github.com"
        git config --local user.name "github-actions"

        # سوییچ به شاخه‌ای که محافظت نشده
        git checkout sepehr21ar-patch-1

        git add -A
        git commit -m "Update scraped data" || echo "No changes to commit"

        git push origin sepehr21ar-patch-1
